apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-ui
    spec:
      containers:
        - name: weatherapp-ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: IfNotPresent
          env:
          - name: AUTH_HOST
            value: {{ .Release.Name }}-auth
          - name: AUTH_PORT
            value: {{ .Values.auth.port | quote }}
          - name: WEATHER_HOST
            value: {{ .Release.Name }}-api
          - name: WEATHER_PORT
            value: {{ .Values.api.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http