apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-api
    spec:
      containers:
        - name: weather-api
          image: {{ .Values.api.image }}
          imagePullPolicy: IfNotPresent
          env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-api-secret
                key: apikey
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http