apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ .Values.auth.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-auth