apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-auth
    spec:
      containers:
      - name: weatherapp-auth
        image: {{ .Values.auth.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.auth.port }}
        env:
          - name: DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: DB_USER
            value: elshwihi
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-secret
                key: auth-password
          - name: DB_NAME
            value: weatherapp
          - name: DB_PORT
            value: "3306"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-secret
                key: secret-key