apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mysql-init-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: mysql-init-container
        image: {{ .Values.auth.db.image }}
        env:
        - name: MYSQL_USER
          value: "elshwihi"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: root-password
        - name: MYSQL_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: auth-password
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql  # Set the MySQL Service name or hostname
        - name: MYSQL_PORT
          value: "3306"  # MySQL port, default is 3306
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 100
          mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
          CREATE DATABASE IF NOT EXISTS weatherapp;
          CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
          GRANT ALL PRIVILEGES ON weatherapp.* TO '${MYSQL_USER}'@'%';
          FLUSH PRIVILEGES;
          EOF
      restartPolicy: Never