apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  auth-password: <>
  root-password: <>
  secret-key: <>